language: julia
os:
  - linux
julia:
  - nightly
  - 1.0.3
cache:
 directories:
   - /home/travis/.julia
addons:
  apt_packages:
  - gfortran
# before_install:
#     # don't keep an old version of the code in the cache
#   - julia -e 'using Pkg'
#   - julia -e 'if "MathProgComplex" in keys(Pkg.installed()) Pkg.rm("MathProgComplex"); Pkg.rm("MathProgComplex") end'
#   - julia -e 'Pkg.update()' #make sure we get the latest version of METADATA
#   - julia -e 'if !("Coverage" in keys(Pkg.installed())) Pkg.add("Coverage") end'
#   - julia -e 'if !("Documenter" in keys(Pkg.installed())) Pkg.add("Documenter") end'
#   - julia -e 'if !("OPFInstances" in keys(Pkg.installed())) Pkg.clone("https://github.com/JulieSliwak/OPFInstances.jl.git") end'
script:
  - if [[ -a .git/shallow ]]; then git fetch --unshallow; fi
  # - julia -e 'using Pkg; Pkg.clone(pwd()); Pkg.test("MathProgComplex", coverage=true)'
  - julia --project -e 'import Pkg; Pkg.build(); Pkg.instantiate()'
  - julia --project -e 'import Pkg; Pkg.test(coverage=true);'
  # - julia -e 'Pkg.clone(pwd())'
  # - julia -e 'Pkg.test("MathProgComplex", coverage=true)'
after_success:
  - julia -e  'using Coverage; cd(Pkg.dir("MathProgComplex")); LCOV.writefile("lcov.info", process_folder(".")); run(pipeline(`curl -s https://codecov.io/bash`, `bash`))'
  # - julia -e 'cd(Pkg.dir("MathProgComplex")); include(joinpath("docs", "make.jl"))'
